language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
env:
  global:
    - secure: "YdzOX2oDdL1Yv0bUKFqco3/bNQ9S+nuPrQ5xaelZMw4qrjUczbJiin5mRnz5tPJbgwMyHghxiNsKMuENoyRLxTbu+ADcZUu1SAIDplc/Cqv9vG/L2GJZBLcJg69utV2AhwhKB2Zsndwy5wr2q96wfSuj/cpqg2spVpUcNk1aImI="
    - "REPOSITORY=visualcaptcha-node"
after_success:
    "curl --data 'deploy={\"repository\":\"'$REPOSITORY'\",\"branch\":\"'$TRAVIS_BRANCH'\"}' http://githooks.emotionloop.com/?k=$AUTH_KEY"
